describe('dwm_bar', function()
	require('dwm_bar')

	describe('timestamp', function()
		it('should return a complete formatted date and time', function()
			local actual = timestamp()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)

	describe('plugged_in', function()
		it('should return plugged when apm return 1', function()
			local actual = plugged_in()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)

	describe('power_percentage_left', function()
		it('should return percentage power', function()
			local actual = power_percentage_left()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)

	describe('memory', function()
		it('should return used and available memory in percentages', function()
			local actual = memory()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)

	describe('cpu', function()
		it('should return user and idle percentages', function()
			local actual = cpu()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)

	describe('network', function()
		it('should return ip and up and down statistics', function()
			local actual = network()
			print("'" .. actual .. "'")
			assert.is.not_falsy(actual)
		end)
	end)
end)
